Pull Request for Portfolio Website
Solobarine/Portfolio_Website pull request #1
Opened 2022-06-30 13:41 UTC by Solobarine

First pull reqiest

2022-06-30 15:51 UTC, mukhammadrizooff requested changes
Hi @Solobarine, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media3.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- No linter errors ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-30 15:51 UTC, mukhammadrizooff commented on index.html
> +    </div>
- [ ] [REQUIRED] The list of icons uses a `ul` tag to group them, and `li` per icon; each icon should has a link (`a` tag). Please make changes!

2022-06-30 15:51 UTC, mukhammadrizooff commented on styles.css
> +}
- [ ] [REQUIRED] Please make changes! Please restyle your project according to Figma design because your design is not like [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=48%3A27).

![image](https://user-images.githubusercontent.com/63915024/176721474-19a830a8-3c90-44e3-8d3f-fb2ebcfb24f0.png)

2022-07-01 00:44 UTC, omarsalem7 requested changes
Hi @Solobarine , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![Almost near](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

 ## Highlights
✔️ All linter checks pass
✔️ Descriptive commit message

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-01 00:44 UTC, omarsalem7 commented on index.html
> +      </div>
- [ ] kindly work in your project to match the one in the Figma not extract the whole image from design and add it.

2022-07-01 11:54 UTC, codecaiine approved these changes
Hi @Solobarine , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
:heavy_check_mark: Good UI
:heavy_check_mark: Good project implementation

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-01 11:54 UTC, codecaiine commented on index.html
> +          <img src="/Image/social media/github_1.png" alt="my github handle" width="20" height="20"></a>
- [ ] [OPTIONAL] Please change your image path from ` src="/Image/social media/github_1.png" ` to ` src="./Image/social media/github_1.png" `

2022-07-01 12:25 UTC, merged